# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Test
        run: mvn test

      - name: Upload Cucumber JSON Report to Jira
        env:
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        run: |
          curl -X POST https://c4j.cucumber.io/ci/rest/api/results \
          -H 'authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjb20uc21hcnRiZWFyLmN1Y3VtYmVyIiwiYXVkIjoiY2kiLCJjb250ZXh0Ijp7ImxpdmluZ19kb2NfaWQiOjUwNjF9LCJpYXQiOjE3MzA4MDY1NzZ9.9BV97eG5UifKti-ZcZ9MOSvrjnkuW0UIs3wZKhHr8Lo' \
          -H 'content-type: application/json' \
          -F 'results_files[]'=@target/cucumber-report.json \
          -F language=jvm